### ISSUE TITLE
不能运行

### ISSUE THREAD

**Issue by zhoupIT** [HotWordland/AssetsPickerToUpLoad#1]
下载下来就会报错

**Comment by HotWordland** [comment]
pod install 执行了吗?

**Comment by zhoupIT** [comment]
下载下来默认是pod 过的呀

**Comment by HotWordland** [comment]
@zhoupIT 因为项目pod的版本比较早了 在podfile需要加上target end 关键字 重新执行pod install
附图:

![14a3008c-1b98-4042-b863-c5eee8104a63](https://cloud.githubusercontent.com/assets/6984865/21126531/d5e3b47a-c127-11e6-98d0-bbc47185918e.png)

**Comment by zhoupIT** [comment]
噢噢,多谢
